### ISSUE TITLE
How do I install fb on Windows?

### ISSUE THREAD

**Issue by martinusso** [rowland/fb#20]
I ran `gem install fb`  and the output was:

Fetching: fb-0.7.0.gem (100%)
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing fb:
        ERROR: Failed to build gem native extension.

```
C:/Ruby/200/bin/ruby.exe extconf.rb
```

checking for main() in -lfbclient... no
checking for main() in -lgds... no
checking for main() in -lfbclient_ms... yes
checking for isc_attach_database() in ibase.h... yes
creating Makefile

make
generating fb-i386-mingw32.def
compiling fb.c
fb.c: In function 'tm_from_timestamp':
fb.c:321:22: warning: unused variable 'tobj'
linking shared-object fb.so

make install
/usr/bin/install -c -m 0755 fb.so C:/Ruby/200/lib/ruby/gems/2.0.0/gems/fb-0.7.0/.
/usr/bin/install: `fb.so' and`C:/Ruby/200/lib/ruby/gems/2.0.0/gems/fb-0.7.0/./fb.so' are the same file
make: **\* [install-so] Error 1

Gem files will remain installed in C:/Ruby/200/lib/ruby/gems/2.0.0/gems/fb-0.7.0 for inspection.
Results logged to C:/Ruby/200/lib/ruby/gems/2.0.0/gems/fb-0.7.0/./gem_make.out

**Comment by YuliemAlavez** [comment]
I had the same mistake. I fix it install firebird 1.5 . Here the link http://www.firebirdsql.org/en/firebird-1-5/

Good Luck.
