### ISSUE TITLE
Segfaulting on database connection

### ISSUE THREAD

**Issue by AnthonyDeSimone** [rowland/fb#38]
I'm running fb (0.7.4) with Ruby 2.0.0-p576 (x64) on a Windows 8 machine. When I attempt to connect to a database, Ruby sefgaults with no obviously useful information.

**Comment by mariuz** [comment]
please use x64-64bit mingw ruby also firebird x64 , see the related issue 

http://stackoverflow.com/a/31059903/66242

**Comment by mariuz** [comment]
This can be closed as it seems to be a 32/64 bits lib missmatch

**Comment by rowland** [comment]
Thanks
