### ISSUE TITLE
clean codebase

### ISSUE THREAD

**Issue by vizcay** [rowland/fb#39]
Hi Rowland, after my first incursion with this gem (and a ruby c extension) I'm thinking a few ways to improve the gem aesthetically speaking to encourage collaboration so it's no so intimidating to newcomers:

- fb.c is too long (3200 LOC), why not separate it by class?
- set on a standard for whitespace: remove tabs and set on 2 or 4 spaces width?
- remove trailing whitespaces
- remove old commented code
- better format for README, also with instructions how to colaborate (or a link maybe)

So, the codebase will remain the same.. what do you think? I can have a pull requests in the near future if you agree.

By the way, are you going to bump version to 0.8 and push to rubygems master?

**Comment by mariuz** [comment]
this i guess can be closed 

i started with remove old commented code , and the rest can be contributed with pull requests on the issue with better readme
