### ISSUE TITLE
Read Uncommitted: Illegal transaction option was specified

### ISSUE THREAD

**Issue by rzane** [rowland/fb#42]
READ UNCOMMITTED transactions don't seem to work. I get an error `Illegal transaction option was specified`.

```ruby
require 'fb'
db = Fb::Database.new(database: "localhost:#{File.expand_path('../db/example.fdb', __FILE__)}")
conn = db.connect rescue db.create.connect

begin
  conn.execute("CREATE TABLE TEST (NAME VARCHAR(20))") if !conn.table_names.include?("TEST")
  conn.transaction 'READ UNCOMMITTED'
  conn.execute("INSERT INTO TEST VALUES (?)", 'Test')
  conn.commit
ensure
  conn.close
end
```

**Comment by rowland** [comment]
Firebird does not support READ UNCOMMITTED.

**Comment by rzane** [comment]
Are you sure? http://www.firebirdsql.org/manual/isql-transactions.html

**Comment by rowland** [comment]
http://www.firebirdsql.org/en/sql-conformance/

See the row F111-01.

**Comment by rzane** [comment]
Okay. Thanks!

**Comment by mariuz** [comment]
I have add a notice to firebird-devel  , seems that needs to be implemented (or only surfaced)
Also i will open a jira ticket

**Comment by helebor** [comment]
You must be kidding, Marius!
