### ISSUE TITLE
rake LoadError 126

### ISSUE THREAD

**Issue by woblavobla** [rowland/fb#50]
Something is wrong with fb on my pc. `LoadError: 126: �� ������ ��������� ������.   - C:/Ruby23/lib/ruby/gems/2.3.0/gems/fb-0.8.0/fb.so`
I tried to user different versions of ruby, but it didn't helped.

**Comment by rowland** [comment]
Google "LoadError: 126" and you'll see similar reports for several native gems with similar solutions to each.
