### ISSUE TITLE
dyld: lazy symbol binding failed

### ISSUE THREAD

**Issue by f-lima** [rowland/fb#57]
dyld: lazy symbol binding failed: Symbol not found: _isc_attach_database
  Referenced from: ~/.rvm/gems/ruby-2.3.0/gems/fb-0.8.0/fb.bundle
  Expected in: flat namespace

dyld: Symbol not found: _isc_attach_database
  Referenced from: ~/.rvm/gems/ruby-2.3.0/gems/fb-0.8.0/fb.bundle
  Expected in: flat namespace

I am running FirebirdCS-2.5.7-27050-i386 with fb 0.8.0 and Ruby 2.3.0 on macOS 10.12 (Sierra).

I can connect using .Net and Java drivers but not using Ruby driver.

**Comment by rowland** [comment]
Your 64-bit Ruby cannot load your 32-bit Firebird library. You'll want the 64-bit Firebird.

**Comment by f-lima** [comment]
I reinstalled the Firebird using the 64 bits package FirebirdCS-2.5.7-27050-x86_64.pkg but I am still getting the same error:

dyld: lazy symbol binding failed: Symbol not found: _isc_attach_database
  Referenced from: ~/.rvm/gems/ruby-2.3.0/gems/fb-0.8.0/fb.bundle
  Expected in: flat namespace

dyld: Symbol not found: _isc_attach_database
  Referenced from: ~/.rvm/gems/ruby-2.3.0/gems/fb-0.8.0/fb.bundle
  Expected in: flat namespace

**Comment by rowland** [comment]
Upgrading Firebird on Mac has not always gone smoothly for me either. From the error messages, you're encountering the exact same issue, so I'm thinking the upgrade did not succeed and it's still trying to link against a 32-bit library.

**Comment by f-lima** [comment]
I deleted the Firebird user and Framework folder installed the new package and restarted the computer. I don't know if I should delete any other file. But the error are still there :(
Do you have any suggestion?

**Comment by rowland** [comment]
A colleague mentioned that he got past an error like that using "gem pristine fb." Basically, there may be build artifacts referencing the old framework.

**Comment by f-lima** [comment]
Solved. Thanks.

**Comment by arius** [comment]
136 / 5000
Výsledky překladu
I have a similar problem. I installed the latest version of Firebird-3.0.7-33374-x86_64.pkg
MacOS 11.4 with M1

I have no idea where the problem may be. 

Problem is not in bundle install, but on the request, where FB connect is usining.

`dyld: lazy symbol binding failed: Symbol not found: _isc_attach_database
`

**Comment by vizcay** [comment]
> I have a similar problem. I installed the latest version of Firebird-3.0.7-33374-x86_64.pkg
> MacOS 11.4 with M1
> 
> I have no idea where the problem may be.
> 
> Problem is not in bundle install, but on the request, where FB connect is usining.
> 
> `dyld: lazy symbol binding failed: Symbol not found: _isc_attach_database `

@arius have you found a solve? I have the exact problem on MacOS Mojave..

**Comment by arius** [comment]
> > I have a similar problem. I installed the latest version of Firebird-3.0.7-33374-x86_64.pkg
> > MacOS 11.4 with M1
> > I have no idea where the problem may be.
> > Problem is not in bundle install, but on the request, where FB connect is usining.
> > `dyld: lazy symbol binding failed: Symbol not found: _isc_attach_database `
> 
> @arius have you found a solve? I have the exact problem on MacOS Mojave..

Still not.

**Comment by vizcay** [comment]
I know that I've solved it now.. but don't ask me how at this point.
