### ISSUE TITLE
Insert with return clause broken in 0.9.0

### ISSUE THREAD

**Issue by jwood381** [rowland/fb#66]
When migrating code to a new server I found that code which works with 0.7.0 fails with 0.9.0. I tested to make sure it was not a ruby or firebird issue. The insert statement succeeds but attempting to retrieve the expected value from the cursor fails with: " The cursor identified in an OPEN statement is already open."

**Comment by rowland** [comment]
I was not aware that that ever worked. Certainly we have no tests in the suite to prove it.

**Comment by jwood381** [comment]
Not sure how I got so off track. Seems to be a configuration issue. My aplogies.
