### ISSUE TITLE
Can't install fb gem in ruby windows 64bits...

### ISSUE THREAD

**Issue by adrianlmm** [rowland/fb#76]
It works fine with ruby 32 bits, but can't install it with ruby 64 bits.

**Comment by mariuz** [comment]
I guess this can be closed with this fix : Windows 64 support added https://github.com/rowland/fb/pull/77

**Comment by adrianlmm** [comment]
I can  confirm that is working.

**Comment by mariuz** [comment]
@adrianlmm please close the issue
