### ISSUE TITLE
fb.c:41:10: fatal error: ibase.h: No such file or directory

### ISSUE THREAD

**Issue by francescovignola** [rowland/fb#80]
I'm trying to install gem fb on ubuntu 22.04 (in wsl2) but I have the error reported in the title.

The steps I follow are:
1. clone of the repository: `git clone https://github.com/rowland/fb.git`
2. build of fb.gemspec `cd fb && gem build fb.gemspec` with success
`Successfully built RubyGem`
`Name: fb`
`Version: 0.9.3`
`File: fb-0.9.3.gem`
3. install fb `gem install fb-0.*.*.gem`:
`Building native extensions. This could take a while...`
`ERROR:  Error installing fb:`
`ERROR: Failed to build gem native extension.` 
`current directory: /home/frank/.gem/gems/fb-0.9.3`
`/usr/bin/ruby3.0 -I /usr/lib/ruby/vendor_ruby -r ./siteconf20230217-1500-q4864.rb extconf.rb`
`checking for isc_attach_database() in -lfbclient... no`
`checking for isc_attach_database() in -lgds... no`
`creating Makefile` 
`current directory: /home/frank/.gem/gems/fb-0.9.3`
`make DESTDIR\=`
`compiling fb.c`
`fb.c:41:10: fatal error: ibase.h: No such file or directory`
   `41 | #include <ibase.h>`
     ` |          ^~~~~~~~~`
`compilation terminated.`
`make: *** [Makefile:245: fb.o] Error 1` 
`make failed, exit code 2` 
`Gem files will remain installed in /home/frank/.gem/gems/fb-0.9.3 for inspection.`
`Results logged to /home/frank/.gem/extensions/x86_64-linux/3.0.0/fb-0.9.3/gem_make.out`

The result logged into /home/frank/.gem/extensions/x86_64-linux/3.0.0/fb-0.9.3/gem_make.out contains the above error.

**Comment by mariuz** [comment]
@francescovignola you need firebird devel headers

https://packages.ubuntu.com/focal/firebird-dev

**Comment by francescovignola** [comment]
> @francescovignola you need firebird devel headers
> 
> https://packages.ubuntu.com/focal/firebird-dev

Thank you! It works!

**Comment by mariuz** [comment]
@francescovignola please close the issue
